---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
  - name: azure-blobstore-resource

run:
  path: azure-blobstore-resource/ci/tasks/prepare-workspace/task.sh
