---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ubuntu

inputs:
  - name: azure-blobstore-resource
  - name: configuration

params:
  CONFIGURATION_FILENAME:

run:
  path: azure-blobstore-resource/example/tasks/print-config/task.sh
