resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: czero/azure-blobstore-resource

resources:
- name: azure-blobstore-resource
  type: git
  source:
    uri: https://github.com/pivotal-cf/azure-blobstore-resource.git
    branch: master

- name: azure-blobstore-resource-image
  type: docker-image
  source:
    repository: czero/azure-blobstore-resource
    username: {{dockerhub_username}}
    password: {{dockerhub_password}}

jobs:
- name: run-tests
  plan:
  - aggregate:
    - get: azure-blobstore-resource
      trigger: true
  - task: run-tests
    file: azure-blobstore-resource/ci/tasks/run-tests/task.yml
    params:
      TEST_STORAGE_ACCOUNT_NAME: {{azure_account_name}}
      TEST_STORAGE_ACCOUNT_KEY: {{azure_account_key}}

- name: build-image-rc
  plan:
  - aggregate:
    - get: azure-blobstore-resource
      passed: [run-tests]
      trigger: true
  - task: prepare-workspace
    file: azure-blobstore-resource/ci/tasks/prepare-workspace/task.yml
  - put: azure-blobstore-resource-image
    params:
      build: azure-blobstore-resource
      tag: azure-blobstore-resource/tag
