resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource

- name: azure-blobstore-rc
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource
    tag: release-candidate

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: azure-blobstore-resource
  type: git
  source:
    uri: https://github.com/pivotal-cf/azure-blobstore-resource.git
    branch: master

- name: pull-requests
  type: pull-request
  source:
    repo: pivotal-cf/azure-blobstore-resource
    access_token: ((github_pr_access_token))

- name: azure-blobstore-resource-rc-image
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource
    username: ((dockerhub_username))
    password: ((dockerhub_password))
    tag: release-candidate

- name: azure-blobstore-resource-final-image
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: base-image
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs3

- name: some-blob-on-azure-rc
  type: azure-blobstore-rc
  source:
    storage_account_name: ((test_rc_storage_account_name))
    storage_account_key: ((test_rc_storage_account_key))
    container: ((test_rc_container))
    versioned_file: some-file

jobs:
- name: run-tests
  plan:
  - aggregate:
    - get: azure-blobstore-resource
      trigger: true
  - task: run-tests
    file: azure-blobstore-resource/ci/tasks/run-tests/task.yml
    params:
      TEST_STORAGE_ACCOUNT_NAME: ((azure_account_name))
      TEST_STORAGE_ACCOUNT_KEY: ((azure_account_key))

- name: bump-rc-image
  plan:
  - aggregate:
    - get: azure-blobstore-resource
      passed: [run-tests]
      trigger: true
    - get: base-image
      trigger: true
  - task: prepare-workspace
    file: azure-blobstore-resource/ci/tasks/prepare-workspace/task.yml
  - put: azure-blobstore-resource-rc-image
    params:
      build: workspace

- name: test-put-rc
  plan:
  - aggregate:
    - get: azure-blobstore-resource
      passed: [bump-rc-image]
      trigger: true
  - task: write-config
    file: azure-blobstore-resource/example/tasks/write-config/task.yml
    params:
      CONFIGURATION_FILENAME: some-file
  - put: some-blob-on-azure-rc
    params:
      file: configuration/some-file

- name: test-get-rc
  plan:
  - aggregate:
    - get: azure-blobstore-resource
      passed: [test-put-rc]
      trigger: true
    - get: some-blob-on-azure-rc
      passed: [test-put-rc]
  - task: print-config
    file: azure-blobstore-resource/example/tasks/print-config/task.yml
    input_mapping:
      configuration: some-blob-on-azure-rc
    params:
      CONFIGURATION_FILENAME: some-file

- name: bump-final-image
  plan:
  - aggregate:
    - get: azure-blobstore-resource
      passed: [test-get-rc]
    - get: base-image
      trigger: true
  - task: prepare-workspace
    file: azure-blobstore-resource/ci/tasks/prepare-workspace/task.yml
  - put: azure-blobstore-resource-final-image
    params:
      build: workspace

- name: run-pr-tests
  plan:
  - aggregate:
    - get: azure-blobstore-resource
      resource: pull-requests
  - task: run-tests
    file: azure-blobstore-resource/ci/tasks/run-tests/task.yml
    params:
      TEST_STORAGE_ACCOUNT_NAME: ((azure_account_name))
      TEST_STORAGE_ACCOUNT_KEY: ((azure_account_key))
