resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource

- name: azure-blobstore-rc
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource
    tag: release-candidate

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:
- name: azure-blobstore-resource
  type: git
  source:
    uri: git@github.com:pivotal-cf/azure-blobstore-resource.git
    branch: master
    private_key: ((github_deploy_key))

- name: pull-requests
  type: pull-request
  source:
    repo: pivotal-cf/azure-blobstore-resource
    access_token: ((github_pr_access_token))

- name: azure-blobstore-resource-rc-image
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource
    username: ((dockerhub_username))
    password: ((dockerhub_password))
    tag: release-candidate

- name: azure-blobstore-resource-final-image
  type: docker-image
  source:
    repository: pcfabr/azure-blobstore-resource
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: base-image
  type: docker-image
  source:
    repository: cloudfoundry/cflinuxfs3

- name: a-versioned-blob
  type: azure-blobstore-rc
  source:
    storage_account_name: ((test_rc_storage_account_name))
    storage_account_key: ((test_rc_storage_account_key))
    container: ((test_rc_container))
    versioned_file: some-versioned-blob

- name: a-regexp-blob
  type: azure-blobstore-rc
  source:
    storage_account_name: ((test_rc_storage_account_name))
    storage_account_key: ((test_rc_storage_account_key))
    container: ((test_rc_container))
    regexp: some-file-(.*)

- name: version
  type: semver
  source:
    driver: git
    uri: git@github.com:pivotal-cf/azure-blobstore-resource.git
    branch: version
    file: current-version
    private_key: ((github_deploy_key))
    initial_version: 0.0.0

- name: github-release
  type: github-release
  source:
    owner: pivotal-cf
    repository: azure-blobstore-resource
    access_token: ((github_release_access_token))

jobs:
- name: run-tests
  plan:
  - in_parallel:
    - get: azure-blobstore-resource
      trigger: true
  - task: run-tests
    file: azure-blobstore-resource/ci/tasks/run-tests/task.yml
    params:
      TEST_STORAGE_ACCOUNT_NAME: ((azure_account_name))
      TEST_STORAGE_ACCOUNT_KEY: ((azure_account_key))

- name: bump-rc-image
  plan:
  - in_parallel:
    - get: azure-blobstore-resource
      passed: [run-tests]
      trigger: true
    - get: base-image
      trigger: true
  - task: prepare-workspace
    file: azure-blobstore-resource/ci/tasks/prepare-workspace/task.yml
  - put: azure-blobstore-resource-rc-image
    params:
      build: workspace

- name: test-versioning-put-rc
  plan:
  - in_parallel:
    - get: azure-blobstore-resource
      passed: [bump-rc-image]
      trigger: true
  - task: write-config
    file: azure-blobstore-resource/example/tasks/write-config/task.yml
    params:
      CONFIGURATION_FILENAME: some-file
  - put: a-versioned-blob
    params:
      file: configuration/some-file

- name: test-versioning-get-rc
  plan:
  - in_parallel:
    - get: azure-blobstore-resource
      passed: [test-versioning-put-rc]
      trigger: true
    - get: a-versioned-blob
      passed: [test-versioning-put-rc]
  - task: print-config
    file: azure-blobstore-resource/example/tasks/print-config/task.yml
    input_mapping:
      configuration: a-versioned-blob
    params:
      CONFIGURATION_FILENAME: some-versioned-blob

- name: test-regexp-put-rc
  plan:
  - in_parallel:
    - get: azure-blobstore-resource
      passed: [bump-rc-image]
      trigger: true
  - task: write-config
    file: azure-blobstore-resource/example/tasks/write-config/task.yml
    params:
      CONFIGURATION_FILENAME: some-file
      APPEND_TIMESTAMP_ON_FILENAME: 1
  - put: a-regexp-blob
    params:
      file: configuration/some-file-*

- name: test-regexp-get-rc
  plan:
  - in_parallel:
    - get: azure-blobstore-resource
      passed: [test-regexp-put-rc]
      trigger: true
    - get: a-regexp-blob
      passed: [test-regexp-put-rc]
  - task: print-config
    file: azure-blobstore-resource/example/tasks/print-config/task.yml
    input_mapping:
      configuration: a-regexp-blob
    params:
      CONFIGURATION_FILENAME: some-file-*

- name: ship-minor
  plan:
  - get: azure-blobstore-resource
    passed: [test-versioning-get-rc, test-regexp-get-rc]
  - put: version
    params: {bump: minor}

- name: base-image-patch
  plan:
  - get: base-image
    trigger: true
  - put: version
    params: {bump: patch}

- name: bump-final-image
  plan:
  - in_parallel:
    - get: azure-blobstore-resource
      passed: [ship-minor]
      trigger: true
    - get: base-image
      passed: [base-image-patch]
      trigger: true
    - get: version
  - in_parallel:
    - task: prepare-workspace
      file: azure-blobstore-resource/ci/tasks/prepare-workspace/task.yml
    - task: prepare-image-labels
      file: azure-blobstore-resource/ci/tasks/prepare-image-labels/task.yml
  - put: azure-blobstore-resource-final-image
    params:
      build: workspace
      additional_tags: version/version
      labels_file: image-labels/labels.json
  - put: azure-blobstore-resource
    params:
      repository: azure-blobstore-resource
      tag: version/version
      only_tag: true
      tag_prefix: v

- name: create-github-release
  plan:
  - in_parallel:
    - get: azure-blobstore-resource
      passed: [bump-final-image]
      trigger: true
    - get: azure-blobstore-resource-final-image
    - get: base-image
      passed: [bump-final-image]
      trigger: true
    - get: version
  - task: prepare-github-release
    file: azure-blobstore-resource/ci/tasks/prepare-github-release/task.yml
  - put: github-release
    params:
      name: github-release/name
      tag: version/version
      tag_prefix: v
      body: github-release/body

- name: run-pr-tests
  plan:
  - in_parallel:
    - get: azure-blobstore-resource
      resource: pull-requests
  - task: run-tests
    file: azure-blobstore-resource/ci/tasks/run-tests/task.yml
    params:
      TEST_STORAGE_ACCOUNT_NAME: ((azure_account_name))
      TEST_STORAGE_ACCOUNT_KEY: ((azure_account_key))
