resource_types:
- name: azure-blobstore
  type: docker-image
  source:
    repository: czero/azure-blobstore-resource

resources:
- name: azure-blobstore-resource
  type: git
  source:
    uri: git@github.com:pivotal-cf/azure-blobstore-resource.git
    branch: master
    private_key: ((git_private_key))

- name: azure-blobstore-resource-image
  type: docker-image
  source:
    repository: czero/azure-blobstore-resource
    username: ((dockerhub_username))
    password: ((dockerhub_password))

- name: base-image
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: base

jobs:
- name: run-tests
  plan:
  - aggregate:
    - get: azure-blobstore-resource
      trigger: true
  - task: run-tests
    file: azure-blobstore-resource/ci/tasks/run-tests/task.yml
    params:
      TEST_STORAGE_ACCOUNT_NAME: ((azure_account_name))
      TEST_STORAGE_ACCOUNT_KEY: ((azure_account_key))

- name: bump-image
  plan:
  - aggregate:
    - get: azure-blobstore-resource
      passed: [run-tests]
      trigger: true
    - get: base-image
      trigger: true
  - task: prepare-workspace
    file: azure-blobstore-resource/ci/tasks/prepare-workspace/task.yml
  - put: azure-blobstore-resource-image
    params:
      build: workspace
