---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: golang

inputs:
  - name: azure-blobstore-resource

run:
  path: azure-blobstore-resource/ci/tasks/run-tests/task.sh

params:
  TEST_STORAGE_ACCOUNT_NAME:
  TEST_STORAGE_ACCOUNT_KEY:
